/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "easyiot.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(io_description, io_description, AUTO)


PB_BIND(device_description, device_description, AUTO)


PB_BIND(io_val, io_val, AUTO)


PB_BIND(get_ios, get_ios, AUTO)


PB_BIND(get_ios_resp, get_ios_resp, AUTO)


PB_BIND(set_ios, set_ios, AUTO)





