#include "stm32f1xx_hal.h"
#include "snet.h"
#include "led.h"

/* TODO: Think about a tidy way to make this work. It's located in the
 * autogenerated cube stuff, but we need to have our own declaration. */
void SystemClock_Config(void);


int
main(void)
{
    HAL_Init();
    SystemClock_Config();

    __HAL_RCC_GPIOC_CLK_ENABLE();

    /* Configure our LED. */
    GPIO_InitTypeDef gpio;

    gpio.Pin = GPIO_PIN_13;
    gpio.Mode = GPIO_MODE_OUTPUT_PP;
    gpio.Pull = GPIO_NOPULL;
    gpio.Speed = GPIO_SPEED_FREQ_LOW;

    HAL_GPIO_Init(GPIOC, &gpio);
    HAL_GPIO_WritePin(GPIOC, GPIO_PIN_13, GPIO_PIN_RESET);

    printf("Hello, world!\n");

    LED_init();
    snet_init();

    uint32_t loop_PKT = 0, loop_LED = 0;

    setPWM(TIM_CHANNEL_1, 0xFFFF / 100 );
    
	while(1)
	{
        uint32_t loop_ms = HAL_GetTick();
        
        if( loop_LED != loop_ms )
        {
            setPWM(TIM_CHANNEL_1, (loop_ms >> 4) & 0xFFFF );
            loop_LED = loop_ms;
        }

        snet_update();
        if( loop_ms - loop_PKT > 250 )
        {
            if( snet_send( NULL, 0, 0xABCD, false, false, 1 ) )
            {
                //poll this untill send every x ms
                loop_PKT = loop_ms; 
                HAL_GPIO_TogglePin(GPIOC, GPIO_PIN_13);
            }
        }

	}
}


void
SysTick_Handler(void)
{
    HAL_IncTick();
}
