#include "stm32f1xx_hal.h"
#include "snet.h"


/* TODO: Think about a tidy way to make this work. It's located in the
 * autogenerated cube stuff, but we need to have our own declaration. */
void SystemClock_Config(void);


int
main(void)
{
    HAL_Init();
    SystemClock_Config();

    __HAL_RCC_GPIOC_CLK_ENABLE();

    /* Configure our LED. */
    GPIO_InitTypeDef gpio;

    gpio.Pin = GPIO_PIN_13;
    gpio.Mode = GPIO_MODE_OUTPUT_PP;
    gpio.Pull = GPIO_NOPULL;
    gpio.Speed = GPIO_SPEED_FREQ_LOW;

    HAL_GPIO_Init(GPIOC, &gpio);
    HAL_GPIO_WritePin(GPIOC, GPIO_PIN_13, GPIO_PIN_RESET);

    printf("Hello, world!\n");

    snet_init();

    int count = 0;
    uint8_t buf[] = {'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'};

    while (1)
    {
        snet_update();

        HAL_GPIO_TogglePin(GPIOC, GPIO_PIN_13);
        HAL_Delay(200);

        if (count == 0)
        {
            snet_send(buf, sizeof(buf));
            count = 10;
        }
        else
        {
            count--;
        }
    }
}


void
SysTick_Handler(void)
{
    HAL_IncTick();
}
